-- SQL DDL script
-- Generated file - do not edit

create table "comments" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"createdAt" TIMESTAMP,"updatedAt" TIMESTAMP,"topic_id" BIGINT NOT NULL,"content" VARCHAR NOT NULL)